name: Laravel Deploy

on:
  workflow_call:
    secrets:
      deploy_host:
        required: true
      deploy_key:
        required: true
      deploy_user:
        required: true
      deploy_path:
        required: true
      deploy_env:
        required: true

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Project
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.deploy_host }}
          key: ${{ secrets.deploy_key }}
          username: ${{ secrets.deploy_user }}

          script: |
            # Navigate to the deployment directory
            cd ${{ secrets.deploy_path }}

            # Set up the environment file
            cat <<EOF > .env
            ${{ secrets.deploy_env }}
            EOF

            # Pull the latest changes from the repository
            git pull origin ${{ github.ref_name }}

            # Install PHP dependencies
            if [ "${{github.ref_name}}" = "develop" ]; then
              composer install --prefer-dist --no-progress --no-suggest --no-interaction
            else
              composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-dev
            fi

            # Handle Laravel specific tasks
            php artisan execute
