name: Laravel Deploy

on:
  workflow_call:
    secrets:
      deploy_host:
        required: true
      deploy_key:
        required: true
      deploy_user:
        required: true
      deploy_path:
        required: true
      deploy_env:
        required: true
      deploy_port:
        required: false

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trust Server
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.deploy_port }} -H ${{ secrets.deploy_host }} >> ~/.ssh/known_hosts

      - name: Deploy Project
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.deploy_host }}
          username: ${{ secrets.deploy_user }}
          key: ${{ secrets.deploy_key }}
          port: ${{ secrets.deploy_port || '22' }}

          script: |
            # Check if the deployment directory exists; if not, clone the repository
            if [ ! -d "${{ secrets.deploy_path }}/.git" ]; then
              echo "Directory does not exist. Starting initial clone..."
              git clone -b ${{ github.ref_name }} git@github.com:${{ github.repository }}.git ${{ secrets.deploy_path }}
            fi

            # Navigate to the deployment directory
            cd ${{ secrets.deploy_path }}

            # Set up the environment file
            cat <<EOF > .env
            ${{ secrets.deploy_env }}
            EOF

            # Ensure the database exists
            DB_NAME=$(grep DB_DATABASE .env | cut -d'=' -f2)
            DB_USER=$(grep DB_USERNAME .env | cut -d'=' -f2)
            DB_PASS=$(grep DB_PASSWORD .env | cut -d'=' -f2)
            
            echo "Checking if database $DB_NAME exists..."
            mysql -u$DB_USER -p$DB_PASS -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

            # Pull the latest changes from the repository
            git pull origin ${{ github.ref_name }}

            # Install PHP dependencies
            if [ "${{github.ref_name}}" = "develop" ]; then
              composer install --prefer-dist --no-progress --no-suggest --no-interaction
            else
              composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-dev
            fi

            # Check if the 'executors' table exists and run migrations if it does not
            TABLE_EXISTS=$(mysql -u$DB_USER -p$DB_PASS $DB_NAME -e "SHOW TABLES LIKE 'executors';" | grep "executors")
            if [ -z "$TABLE_EXISTS" ]; then
                echo "Table 'executors' does not exist. Running migrations..."
                php artisan migrate --force
            fi

            # Handle Laravel specific tasks
            php artisan execute
