name: Development Deploy

on:
  workflow_call:
    inputs:
      deploy_host: 
        required: true
        type: string
      deploy_key:
        required: true
        type: string
      deploy_user: 
        required: true
        type: string
      deploy_path:
        required: true
        type: string
      deploy_env:
        required: true
        type: string

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Project
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ inputs.deploy_host }}
          key: ${{ inputs.deploy_key }}
          username: ${{ inputs.deploy_user }}

          script: |
            cd ${{ inputs.deploy_path }}
            cat <<EOF > .env
            ${{ inputs.deploy_env }}
            EOF
            git pull origin develop
            composer install --prefer-dist --no-progress --no-suggest --no-interaction
            php artisan execute
